version: "3.5"
services:
  isard-database:
    image: postgres
    container_name: "isard-database-devel"
    environment:
      - POSTGRES_USER=isardvdi
      - POSTGRES_PASSWORD=isardvdi
      - POSTGRES_DB=engine
    ports:
      - "5432:5432"
    volumes:
      - "/opt/isard/database:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - isard_network
    restart: "no"

  pgAdmin:
    restart: "no"
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@admin.com
      PGADMIN_DEFAULT_PASSWORD: isardvdi
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - isard_network
      
  isard-nginx:
    image: hello-world
    container_name: isard-nginx-devel
    volumes:
      - "./dockers/nginx/nginx.conf:/etc/nginx/nginx.conf"    
    build:
      context: .
      dockerfile: dockers/nginx/Dockerfile
      target: development
    restart: "no"

  isard-hypervisor:
    image: hello-world
    container_name: isard-hypervisor-devel
    ports:
      - "2022:22"
    build:
      context: .
      dockerfile: dockers/hypervisor/Dockerfile    
      target: development
    restart: "no"

  isard-app:
    container_name: isard-app-devel
    volumes:
      - "./src:/isard"
    ports:
      - "1313:1313"
      - "5555:5555"
    build:
      context: .
      dockerfile: dockers/app/Dockerfile    
      target: development
    restart: "no"

  isard-backend:
    image: hello-world
    container_name: isard-backend-devel
    volumes:
      - "./src/new_webapp/backend:/app"
      - "~/.cache/isard-devel/backend:/go/pkg/mod"
    ports:
      - "1312:1312"
    build:
      target: development

  isard-frontend:
    image: hello-world
    container_name: isard-frontend-devel
    volumes:
      - "./src/new_webapp/frontend:/app"
      - "~/.cache/isard-devel/frontend:/app/node_modules"
    networks:
      - isard_network
    ports:
      - "8080:8080"
    image: node:lts-alpine
    depends_on:
      - isard-backend
    working_dir: "/app"
    command: "sh -c 'yarn && yarn run serve'"
    environment:
      - NODE_ENV=development

  isard-grpcwebproxy:
    container_name: isard-grpcwebproxy-devel
    logging:
      driver: "json-file"

networks:
  isard_network:
    external: false
    name: isard_network

volumes:
  pgadmin:
