version: "3.5"
services:
  chromedriver:
    environment:
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    ports:
      - 5899:5900
    networks:
      - isard_network
    image: blueimp/chromedriver
  nightwatch:
    depends_on:
      - chromedriver
#      - isard-nginx
    environment:
      - WAIT_FOR_HOSTS=isard-nginx:443 chromedriver:4444 chromedriver:6060
    volumes:
      - ./test:/home/node
    image: blueimp/nightwatch:1.0

networks:
  isard_network:
    external: false
    name: isard_network
