version: "3.5"
services:
  isard-vpn:
    build:
      context: ${BUILD_ROOT_PATH}
      dockerfile: docker/vpn/Dockerfile
      target: production
    container_name: isard-vpn      
    cap_add:
      - NET_ADMIN
      - SYS_MODULE  
    networks:
      - isard-network
    ports:
      - published: 51820
        target: 51820
        protocol: udp
    restart: unless-stopped
    env_file:
      - .env         
